name: hn_2018
description: Hacker News Client

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_database: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
